name: Github Actions Pipeline CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    name: Running Unit Tests
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - name: Use Node
      with:
            node-version: 14.x
      run: |
        npm install
        

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        with:
            node-version: 14.x
        run: |
          yarn
          yarn test

  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'https://juan-pre-test.herokuapp.com/'
    needs:
      test
      build
    steps:
      name: 

